# Generated by Django 3.2.18 on 2023-05-08 19:18

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='img',
            field=models.ImageField(upload_to=myapp.models.customer),
        ),
    ]
